catalog/urls.py
from django.urls import path
from catalog import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.AuthorsListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('borrowed/', views.ListOfBooksOnLoanLibrarianVision.as_view(), name='all-borrowed'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

core/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')), 
    path('', RedirectView.as_view(url='/catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.contrib.auth.models import User
from datetime import date
from django.db import models
from django.urls import reverse
import uuid


class Genre(models.Model):
    # Modelo que representa po genero de livro.
    name = models.CharField(max_length=200, help_text='Insira um gênero de livro')

    def __str__(self):
        return self.name


class Book(models.Model):
    # modelo para representar o livro
    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Insira uma breve descrição do livro')

    isbn = models.CharField('ISBN', max_length=13, help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(Genre, help_text='Selecione um gênero para este livro')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    # modelo que representa uma cópia um livro
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='ID exclusivo para este livro específico em toda a biblioteca')

    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
    ('m', 'Em manutenção'),
    ('o', 'Emprestado'),
    ('a', 'Disponível'),
    ('r', 'Reservado'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Disponibilidade de reserva',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Seta devolução do livro'),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    # modelo representando um autor
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Insira uma data entre agora e 4 semanas (padrão: 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Data inválida - renovação já realizada'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Data inválida - renovação com mais de 4 semanas de antecedência'))
        
        return data

catalog/views.py
import datetime

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy

from catalog.models import Book, Author, BookInstance, Genre

from catalog.forms import RenewBookForm

def index(request):
    number_books = Book.objects.all().count()
    number_instances = BookInstance.objects.all().count()

    number_instances_available = BookInstance.objects.filter(status__exact='a').count()

    number_authors = Author.objects.count()

    number_visits = request.session.get('number_visits', 0)
    number_visits += 1
    request.session['number_visits'] = number_visits

    context = {
        'number_books': number_books,
        'number_instances': number_instances,
        'number_instances_available': number_instances_available,
        'number_authors': number_authors,
        'number_visits': number_visits,
    }

    return render(request, 'index.html', context=context)

class AuthorsListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back'))


class ListOfBooksOnLoanLibrarianVision(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = 'catalog/bookinstance_list_of_books_on_loan_librarian_vision.html'

    def get_queryset(self):
        return (BookInstance.objects.filter(status__exact='o').order_by('due_back'))


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # Se for uma solicitação POST, processa os dados do form
    if request.method == 'POST':
        #Instancia um formulario de RenewBookForm e faz o binding dos dados da req.
        form = RenewBookForm(request.POST)

        # Valida o form
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('all-borrowed'))
        
        # Se qualquer outro método, cria-se um form padrão
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(DeleteView):
    model= Author
    success_url = reverse_lazy('authors')

catalog/templates/base_generic.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% block title %}
    <title>West Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% bootstrap_css %}
    {% block extra_css %}{% endblock extra_css %}
  </head>
  <body>

    <div class="d-flex min-vh-100">
        <aside   class="p-3" style="width:260px; background-color: var(--bs-body-bg);" data-bs-theme="dark">
          {% block sidebar %}
          <h5 class="mb-4 text-white">Menu</h5>
          <ul class="nav nav-pills flex-column gap-2">
            <li class="nav-item"><a class="nav-link text-white rounded-0" href="{% url 'index' %}">Inicio</a></li>
            <li><a class="nav-link text-white rounded-0" href="{% url "books" %}">Livros</a></li>
            <li class="nav-item"><a class="nav-link text-white rounded-0" href="{% url "authors" %}">Autores</a></li>

            {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link text-white rounded-0" href="{% url 'my-borrowed' %}">Meus empréstimos</a></li>
              <li class="nav-item text-white"><a class="nav-link text-white rounded-0">User: {{ user.get_username }}</a></li>

              {% if perms.catalog.can_mark_returned %}
                <li class="nav-item text-white"><a class="nav-link text-white rounded-0" href="{% url "all-borrowed" %}">Livros emprestados</a></li>
              {% endif %}
              <li>
                <form method="post" action="{% url 'logout' %}" style="display:inline;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-danger">Sair</button>
                </form>
              </li>              
            {% else %}
              <li class="nav-item text-white"><a class="btn btn-outline-success" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
          </ul>
          {% endblock %}
        </aside>
        <main class="flex-fill p-4">
          {% block content %}{% endblock %}

          {% block pagination %}
            {% if is_paginated %}
              <div class="pagination">
                <span class="page-links">
                  {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
                </span>
              </div>
            {% endif %}
          {% endblock %}
        </main>
    </div>
  </body>
</html>

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Excluir autor</h1>

  <p>Tem certeza de que deseja excluir o autor: {{ author }}</p>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Sim, excluir.">
  </form>
{% endblock content %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Informações do autor</h1>

  {% if author %}
    <h2>{{ author.last_name }}, {{author.first_name}}</h2>
    <p>
      {{ author.date_of_birth }}
      {% if author.date_of_death %}
        – {{ author.date_of_death }}
      {% endif %}
    </p>
  {% else %}
    <p>Não há mais informações sobre o autor.</p>
  {% endif %}
{% endblock content %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Enviar">
  </form>
{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Autores</h1>

  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{author.last_name }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Ainda não há livros cadastrado na biblioteca.</p>
  {% endif %}
{% endblock content %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url "author-detail" book.author.pk %}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }} </p>
  <p><strong>ISBN:</strong> {{ book.isbn }} </p>
  <p><strong>Language:</strong> {{ book.language }} </p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %} {% endfor %} </p>

  <div style="margin-left:20px; margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>

      {% if copy.status != 'a' %}
        <p><strong>Deve ser devolvido:</strong> {{ copy.due_back }}</p>
      {% endif %}

      <p><strong>Selo</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>

  {% endblock content %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Livros</h1>

  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{book.get_absolute_url}}">{{book.title}}</a>
          ({{book.author}})
        </li>
      {% endfor %}
    </ul>
  {% else %}
  <p>Não há livros na biblioteca.</p>
  {% endif %}
{% endblock content %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renovar: {{ book_instance.book.title }}</h1>
  <p>Leitor: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class='text-danger'{% endif %}>Data de vencimento: {{ book_instance.due_back }}</p>


  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Enviar">
  </form>
{% endblock content %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Livros emprestados</h1>

  {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li class='{% if bookinst.is_overdue %}text-danger{% endif %}'>
          <a href="{% url "book-detail" bookinst.book.pk %}">
            {{ bookinst.book.title }}
          </a>
          ({{ bookinst.due_back }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Não há livros emprestados.</p>
  {% endif %}
{% endblock content %}

catalog/templates/catalog/bookinstance_list_of_books_on_loan_librarian_vision.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Livros emprestados</h1>

  {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url "book-detail" bookinst.book.pk %}">
            {{bookinst.book.title}}
          </a>
          ({{ bookinst.due_back }}) - {{bookinst.borrower}} 
          {% if perms.catalog.can_mark_returned %}-
            <a href="{% url "renew-book-librarian" bookinst.id %}">Renovar</a>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Não há livros emprestados.</p>
  {% endif %}
{% endblock content %}

catalog/templates/index.html
{% extends "base_generic.html" %} {% block content %}
<h1>West Library Home</h1>
<p>
  Bem vindo a West Library, um site desenvolvido por
  <em>RangelGs-dev</em>
</p>

<h2>Conteúdo dinâmico (Acervo)</h2>

<p>A biblioteca possui a seguinte quantidade de registros:</p>
<ul>
  <li><strong>Books:</strong> {{number_books}}</li>
  <li><strong>Copies:</strong> {{number_instances}}</li>
  <li><strong>Copies avaiable:</strong> {{number_instances_available}}</li>
  <li><strong>Authors:</strong> {{number_authors}}</li>
</ul>

<p>Você visitou esta página {{ number_visits }} {% if number_visits == 1 %} vez.{% else %} vezes.{% endif %}</p>

{% endblock content %}